local transform = 0--[[$TRANSFORM]]
vert_x = vert_x*transform[1]+vert_y*transform[5]+vert_z*transform[9] +vert_w*transform[13]
vert_y = vert_x*transform[2]+vert_y*transform[6]+vert_z*transform[10]+vert_w*transform[14]
vert_z = vert_x*transform[3]+vert_y*transform[7]+vert_z*transform[11]+vert_w*transform[15]
vert_w = vert_x*transform[4]+vert_y*transform[8]+vert_z*transform[12]+vert_w*transform[16]